# Generated by Django 5.0.6 on 2024-07-31 16:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopapp.women', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статистика статей',
                'verbose_name_plural': 'Статистика статей',
                'db_table': 'PostStatistic',
            },
        ),
    ]
