# Generated by Django 5.0.6 on 2024-07-31 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_articlestatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatistic',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.women', verbose_name='Статья'),
        ),
    ]
