# Generated by Django 5.0.6 on 2024-08-01 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_women_cat_postcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomments',
            options={'ordering': ['-time_create'], 'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='postcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='shopapp.postcomments', verbose_name='Родитель'),
        ),
    ]
