# Generated by Django 5.0.6 on 2024-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_alter_postcomments_options_postcomments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='preview',
            field=models.TextField(blank=True, verbose_name='Превью'),
        ),
    ]
